
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: backend_c
    volumes:
      - ./config:/app/config
    ports:
      - '5001:5000'